- name: LangGraph Python
  llms_txt: https://langchain-ai.github.io/langgraph/llms.txt

- name: CrewAI
  llms_txt: https://docs.crewai.com/llms.txt

- name: Agno
  llms_txt: https://docs.agno.com/llms.txt

- name: Model Context Protocol
  llms_txt: https://modelcontextprotocol.io/llms.txt

- name: Google Gemini
  llms_txt: https://geminibyexample.com/llms.txt

- name: Chainlit
  llms_txt: https://docs.chainlit.io/llms.txt

- name: FastHTML
  llms_txt: https://fastht.ml/docs/llms.txt

- name: Supabase
  llms_txt: https://supabase.com/llms.txt

- name: Pinecone
  llms_txt: https://docs.pinecone.io/llms.txt

- name: Composio
  llms_txt: https://docs.composio.dev/llms.txt

- name: Mem0
  llms_txt: https://docs.mem0.ai/llms.txt

- name: Zep
  llms_txt: https://help.getzep.com/llms.txt

- name: Clerk Auth
  llms_txt: https://clerk.com/docs/llms.txt

- name: Stack Auth
  llms_txt: https://docs.stack-auth.com/llms.txt

- name: Stripe
  llms_txt: https://docs.stripe.com/llms.txt

- name: Resend
  llms_txt: https://resend.com/docs/llms.txt

- name: Upstash
  llms_txt: https://upstash.com/docs/llms.txt

- name: Netlify
  llms_txt: https://docs.netlify.com/llms.txt

- name: Unsloth AI
  llms_txt: https://docs.unsloth.ai/llms.txt